---
- name: create nomad directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ec2-user
  with_items:
    - "{{ nomad_config_dir }}"
    - "{{ nomad_config.data_dir }}"

- name: create main configuration file
  copy:
    dest: "{{ nomad_config_dir }}/00-main.json"
    content: "{{ nomad_config | to_nice_json(indent=2) }}"
