---
- name: Create service nomad
  template:
    src: ../templates/etc/systemd/system/nomad.service.j2
    dest: /etc/systemd/system/nomad.service

- name: Enable service nomad
  service:
    name: nomad
    enabled: yes
